/* WhatsAfrica — 1:1 WebRTC calls
 * Signaling: Supabase Realtime private Broadcast
 * Media: browser WebRTC only; no call media is stored.
 * TURN can be injected with WA_CALL_TURN (array of ICE servers).
 */
(function(){
'use strict';
const DEFAULT_ICE=[{urls:['stun:stun.l.google.com:19302']}];
const state={db:null,user:null,callId:null,channel:null,pc:null,local:null,remote:null,conversationId:null,peerId:null,initiator:false,closed:false};
function cfg(){return Array.isArray(window.WA_CALL_TURN)&&window.WA_CALL_TURN.length?window.WA_CALL_TURN:DEFAULT_ICE}
function ensureUi(){if(document.getElementById('waCallModal'))return;const s=document.createElement('style');s.textContent='.wa-call-modal{position:fixed;inset:0;background:#000c;z-index:9999;display:none;align-items:center;justify-content:center;padding:14px}.wa-call-modal.on{display:flex}.wa-call-box{width:min(900px,100%);background:#101724;border:1px solid #ffffff22;border-radius:20px;padding:16px;color:#fff}.wa-call-videos{display:grid;grid-template-columns:1fr 1fr;gap:10px}.wa-call-videos video{width:100%;aspect-ratio:16/10;object-fit:cover;background:#05070b;border-radius:14px}.wa-call-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.wa-call-actions button{border:0;border-radius:10px;padding:10px 14px;font-weight:800;cursor:pointer}.wa-call-status{color:#aab5c7;margin:8px 0}@media(max-width:700px){.wa-call-videos{grid-template-columns:1fr}}';document.head.appendChild(s);const m=document.createElement('div');m.id='waCallModal';m.className='wa-call-modal';m.innerHTML='<div class="wa-call-box"><div style="display:flex;justify-content:space-between;gap:10px"><div><b>📹 WhatsAfrica</b><div id="waCallStatus" class="wa-call-status">Préparation…</div></div><button onclick="window.WA_CALLS.end()" style="background:transparent;color:#fff;border:0;font-size:24px">×</button></div><div class="wa-call-videos"><video id="waCallLocal" autoplay muted playsinline></video><video id="waCallRemote" autoplay playsinline></video></div><div class="wa-call-actions"><button onclick="window.WA_CALLS.toggleMic()">🎙️ Micro</button><button onclick="window.WA_CALLS.toggleCam()">📷 Caméra</button><button onclick="window.WA_CALLS.end()" style="background:#ef6b67;color:#200">Raccrocher</button></div></div></div>';document.body.appendChild(m)}
function status(t){const e=document.getElementById('waCallStatus');if(e)e.textContent=t}
function show(){ensureUi();document.getElementById('waCallModal').classList.add('on')}
function hide(){const e=document.getElementById('waCallModal');if(e)e.classList.remove('on')}
async function send(event,payload){if(!state.channel)throw new Error('Canal d’appel indisponible');return state.channel.send({type:'broadcast',event,payload:{...payload,callId:state.callId,from:state.user.id}})}
async function prepare(conversationId,peerId,initiator){if(!state.db||!state.user)throw new Error('Session WhatsAfrica requise');state.conversationId=conversationId;state.peerId=peerId;state.initiator=initiator;state.closed=false;if(initiator){const ins=await state.db.from('call_sessions').insert({conversation_id:conversationId,initiator_id:state.user.id,status:'ringing',media_mode:'audio_video'}).select('id').single();if(ins.error)throw ins.error;state.callId=ins.data.id;const p=await state.db.from('call_participants').insert([{call_id:state.callId,user_id:state.user.id,role:'initiator'},{call_id:state.callId,user_id:peerId,role:'participant'}]);if(p.error){await state.db.from('call_sessions').delete().eq('id',state.callId);throw p.error}}state.channel=state.db.channel('call:'+state.callId,{config:{private:true}});state.channel.on('broadcast',{event:'signal'},async({payload})=>{if(!payload||payload.callId!==state.callId||payload.from===state.user.id)return;try{await onSignal(payload)}catch(e){console.warn('signal',e)}});state.channel.on('broadcast',{event:'control'},async({payload})=>{if(!payload||payload.callId!==state.callId||payload.from===state.user.id)return;try{await onControl(payload)}catch(e){console.warn('control',e)}});const sub=await state.channel.subscribe();if(sub!=='SUBSCRIBED'&&sub?.status!=='SUBSCRIBED')throw new Error('Canal sécurisé indisponible');await makePeer()}
async function makePeer(){state.pc=new RTCPeerConnection({iceServers:cfg(),iceCandidatePoolSize:4});state.pc.onicecandidate=e=>{if(e.candidate)send('signal',{kind:'ice',candidate:e.candidate.toJSON()}).catch(()=>{})};state.pc.ontrack=e=>{const v=document.getElementById('waCallRemote');if(v&&e.streams[0]){state.remote=e.streams[0];v.srcObject=e.streams[0]}};state.pc.onconnectionstatechange=()=>{const c=state.pc.connectionState;if(c==='connected')status('Appel connecté');else if(c==='connecting')status('Connexion…');else if(c==='disconnected')status('Réseau instable, reconnexion…');else if(c==='failed')status('Connexion impossible — vérifiez le réseau.');else if(c==='closed')status('Appel terminé')};state.local=await navigator.mediaDevices.getUserMedia({audio:true,video:true});state.local.getTracks().forEach(t=>state.pc.addTrack(t,state.local));const v=document.getElementById('waCallLocal');if(v)v.srcObject=state.local}
async function createOffer(){if(!state.pc)return;const offer=await state.pc.createOffer({offerToReceiveAudio:true,offerToReceiveVideo:true});await state.pc.setLocalDescription(offer);await send('signal',{kind:'offer',description:state.pc.localDescription});status('Connexion…')}
async function onSignal(p){if(!state.pc)return;if(p.kind==='offer'){await state.pc.setRemoteDescription(p.description);const answer=await state.pc.createAnswer();await state.pc.setLocalDescription(answer);await send('signal',{kind:'answer',description:state.pc.localDescription})}else if(p.kind==='answer'){await state.pc.setRemoteDescription(p.description)}else if(p.kind==='ice'&&p.candidate){try{await state.pc.addIceCandidate(p.candidate)}catch(e){console.warn('ICE',e)}}}
async function onControl(p){if(p.action==='end')await finishRemote('ended');if(p.action==='accept'){status('Connexion…');await updateCall('accepted');if(state.initiator)await createOffer()}if(p.action==='reject')await finishRemote('rejected')}
async function updateCall(statusValue){if(!state.callId)return;await state.db.from('call_sessions').update({status:statusValue,...(statusValue==='accepted'?{answered_at:new Date().toISOString()}:{})}).eq('id',state.callId)}
async function finishRemote(s){await updateCall(s);cleanup(false);status(s==='rejected'?'Appel refusé':'Appel terminé');setTimeout(hide,700)}
async function start(conversationId,peerId){try{ensureUi();show();status('Appel en cours…');await prepare(conversationId,peerId,true);await send('control',{action:'ring'});status('Sonnerie chez votre correspondant…')}catch(e){console.error(e);status(e.message||'Impossible de démarrer l’appel.');cleanup(true)}}
async function accept(callId){try{ensureUi();show();state.callId=callId;state.initiator=false;const r=await state.db.from('call_sessions').select('conversation_id,initiator_id').eq('id',callId).single();if(r.error)throw r.error;state.conversationId=r.data.conversation_id;state.peerId=r.data.initiator_id;await prepare(state.conversationId,state.peerId,false);await updateCall('accepted');await send('control',{action:'accept'});status('Connexion…')}catch(e){status(e.message||'Impossible d’accepter.');cleanup(true)}}
async function reject(callId){if(!state.db||!state.user)return;try{state.callId=callId;state.channel=state.db.channel('call:'+callId,{config:{private:true}});const sub=await state.channel.subscribe();if(sub==='SUBSCRIBED'||sub?.status==='SUBSCRIBED'){await send('control',{action:'reject'})}await updateCall('rejected')}catch(e){console.warn('reject',e)}finally{if(state.channel)state.db.removeChannel(state.channel);state.channel=null;state.callId=null}}
async function end(){if(state.callId&&state.channel){try{await send('control',{action:'end'})}catch(e){}}await updateCall('ended');cleanup(true);hide()}
function cleanup(close){if(state.local)state.local.getTracks().forEach(t=>t.stop());if(state.pc)state.pc.close();if(state.channel&&state.db)state.db.removeChannel(state.channel);state.local=null;state.remote=null;state.pc=null;state.channel=null;if(close){state.callId=null;state.conversationId=null;state.peerId=null}}
function toggleMic(){if(!state.local)return;state.local.getAudioTracks().forEach(t=>t.enabled=!t.enabled)}
function toggleCam(){if(!state.local)return;state.local.getVideoTracks().forEach(t=>t.enabled=!t.enabled)}
function init(db,user){state.db=db;state.user=user;ensureUi()}
window.WA_CALLS={init,start,accept,reject,end,toggleMic,toggleCam};
})();
