/* WhatsAfrica Media Engine — client-side guardrails + /3Dbuildboard image quality pipeline. */
(function(){'use strict';
const RULES={image:{maxBytes:6*1024*1024,mimes:['image/jpeg','image/png','image/webp','image/gif']},video:{maxBytes:25*1024*1024,mimes:['video/mp4','video/webm'],maxSeconds:60,maxWidth:1920,maxHeight:1080}};
function validate(file,kind){if(!file)throw new Error('Aucun fichier sélectionné.');const r=RULES[kind];if(!r)throw new Error('Type média non pris en charge.');if(!r.mimes.includes(file.type))throw new Error('Format non autorisé.');if(file.size>r.maxBytes)throw new Error('Fichier trop volumineux. Limite: '+Math.round(r.maxBytes/1024/1024)+' Mo.');return true;}
function inspectVideo(file){validate(file,'video');return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>{const d={duration:v.duration,width:v.videoWidth,height:v.videoHeight};URL.revokeObjectURL(u);if(!Number.isFinite(d.duration)||d.duration>RULES.video.maxSeconds)reject(new Error('Vidéo trop longue. Maximum: '+RULES.video.maxSeconds+' secondes.'));else if(d.width>RULES.video.maxWidth||d.height>RULES.video.maxHeight)reject(new Error('Résolution maximale: 1920×1080.'));else resolve(d)};v.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('Vidéo illisible ou corrompue.'))};v.src=u;});}
async function validateMedia(file,kind){validate(file,kind);return kind==='video'?inspectVideo(file):{width:null,height:null};}
function preview(file,el){if(!el)return;const u=URL.createObjectURL(file);el.onload=()=>URL.revokeObjectURL(u);el.src=u;el.classList.remove('hidden');}
function videoPreview(file,el){if(!el)return;const u=URL.createObjectURL(file);el.onloadeddata=()=>URL.revokeObjectURL(u);el.src=u;el.controls=true;el.muted=true;el.playsInline=true;el.classList.remove('hidden');}
function decodeImage(file){return new Promise((resolve,reject)=>{if(window.createImageBitmap){createImageBitmap(file,{imageOrientation:'from-image'}).then(resolve).catch(()=>fallback(file));return}fallback(file);function fallback(f){const u=URL.createObjectURL(f),img=new Image();img.onload=()=>{URL.revokeObjectURL(u);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('Image illisible ou corrompue.'))};img.src=u;}})}
function convolveSharpen(src,dst,w,h){const s=src.data,d=dst.data;for(let y=1;y<h-1;y++){for(let x=1;x<w-1;x++){const i=(y*w+x)*4;for(let c=0;c<3;c++){const v=5*s[i+c]-s[i-4+c]-s[i+4+c]-s[i-w*4+c]-s[i+w*4+c];d[i+c]=Math.max(0,Math.min(255,v));}d[i+3]=s[i+3];}}for(let x=0;x<w;x++){let i=x*4;d[i]=s[i];d[i+1]=s[i+1];d[i+2]=s[i+2];d[i+3]=s[i+3];i=((h-1)*w+x)*4;d[i]=s[i];d[i+1]=s[i+1];d[i+2]=s[i+2];d[i+3]=s[i+3];}for(let y=1;y<h-1;y++){let i=(y*w)*4,j=(y*w+w-1)*4;for(const k of [i,j]){d[k]=s[k];d[k+1]=s[k+1];d[k+2]=s[k+2];d[k+3]=s[k+3];}}return dst;}
async function enhanceImage(file,opts={}){validate(file,'image');if(file.type==='image/gif'||opts.enabled===false)return file;const img=await decodeImage(file);const sw=img.width||img.naturalWidth,sh=img.height||img.naturalHeight;if(!sw||!sh)throw new Error('Dimensions image invalides.');const max=opts.maxDimension||2400;const scale=Math.min(1,max/Math.max(sw,sh));const w=Math.max(1,Math.round(sw*scale)),h=Math.max(1,Math.round(sh*scale));const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,w,h);if(img.close)img.close();let base=ctx.getImageData(0,0,w,h);if(w>2&&h>2){const work=new ImageData(new Uint8ClampedArray(base.data),w,h);convolveSharpen(base,work,w,h);const strength=Math.min(0.34,Math.max(0.16,1-Math.max(w,h)/2400));for(let i=0;i<base.data.length;i+=4){base.data[i]=base.data[i]*(1-strength)+work.data[i]*strength;base.data[i+1]=base.data[i+1]*(1-strength)+work.data[i+1]*strength;base.data[i+2]=base.data[i+2]*(1-strength)+work.data[i+2]*strength;}ctx.putImageData(base,0,0);}const type=file.type==='image/png'?'image/png':'image/webp';const quality=type==='image/png'?undefined:0.92;const blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Amélioration image impossible.')),type,quality));const ext=type==='image/png'?'png':'webp';return new File([blob],(file.name.replace(/\.[^.]+$/,'')||'image')+'-3dbuildboard.'+ext,{type,lastModified:Date.now()});}
async function enhanceForUpload(file){try{return await enhanceImage(file)}catch(e){console.warn('[WhatsAfrica /3Dbuildboard] image kept original:',e);return file;}}
async function replaceInputFiles(input){if(!input||input.dataset.wa3dBusy==='1'||!input.files?.length)return;const images=Array.from(input.files).filter(f=>/^image\//.test(f.type));if(!images.length)return;input.dataset.wa3dBusy='1';try{const enhanced=[];for(const f of Array.from(input.files)){enhanced.push(/^image\//.test(f.type)?await enhanceForUpload(f):f);}const dt=new DataTransfer();enhanced.forEach(f=>dt.items.add(f));input.files=dt.files;input.dispatchEvent(new CustomEvent('wa:image-enhanced',{bubbles:true,detail:{count:images.length,rule:'/3Dbuildboard'}}));}finally{delete input.dataset.wa3dBusy;}}
function installAutoEnhancement(){const run=e=>{const t=e.target;if(t?.tagName==='INPUT'&&t.type==='file'&&t.files?.length)replaceInputFiles(t);};document.addEventListener('change',run,true);}
window.WhatsAfricaMedia={RULES,validate,validateMedia,preview,videoPreview,enhanceImage,enhanceForUpload,replaceInputFiles,installAutoEnhancement};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installAutoEnhancement,{once:true});else installAutoEnhancement();
})();
