/* WhatsAfrica Voice — encrypted voice media using the existing conversation AES key. */
(function(global){'use strict';
const te=new TextEncoder();
const b64=bytes=>{let s='';const a=new Uint8Array(bytes);for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s)};
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function key(raw){return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encryptBytes(bytes,rawKey,aad){const iv=crypto.getRandomValues(new Uint8Array(12));const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:te.encode(aad)},await key(rawKey),bytes));return{iv,ciphertext:ct}}
async function decryptBytes(bytes,rawKey,iv,aad){return new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:te.encode(aad)},await key(rawKey),bytes))}
function preferredMime(){if(typeof MediaRecorder==='undefined')return null;const types=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4'];return types.find(x=>MediaRecorder.isTypeSupported(x))||null}
async function startRecording(){const mime=preferredMime();if(!mime)throw new Error('Les messages vocaux ne sont pas pris en charge sur cet appareil.');const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const recorder=new MediaRecorder(stream,{mimeType:mime});const chunks=[];const startedAt=Date.now();recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const done=new Promise((resolve,reject)=>{recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());resolve({blob:new Blob(chunks,{type:mime.split(';')[0]}),durationMs:Date.now()-startedAt,mime:mime.split(';')[0]})};recorder.onerror=e=>{stream.getTracks().forEach(t=>t.stop());reject(e.error||new Error('Enregistrement vocal impossible'))}});recorder.start(250);return{recorder,done}}
async function send({db,storage,conversationId,senderId,rawKey,messageId,blob,durationMs,mime}){if(!db||!storage||!conversationId||!senderId||!rawKey||!blob)throw new Error('Message vocal invalide');if(blob.size>8*1024*1024)throw new Error('Message vocal trop volumineux (8 Mo maximum).');const id=messageId||crypto.randomUUID(),aad=`whatsafrica:voice:v1:${conversationId}:${id}`,bytes=new Uint8Array(await blob.arrayBuffer()),enc=await encryptBytes(bytes,rawKey,aad),path=`${senderId}/${conversationId}/${id}.bin`,upload=await storage.from('private-voice').upload(path,new Blob([enc.ciphertext],{type:'application/octet-stream'}),{contentType:'application/octet-stream',upsert:false});if(upload.error)throw upload.error;const payload={id,conversation_id:conversationId,sender_id:senderId,body:null,message_type:'voice',audio_url:null,encryption_version:1,ciphertext:null,encryption_metadata:{v:1,kind:'voice',alg:'AES-256-GCM',iv:b64(enc.iv),aad,media_path:path,media_mime:mime,media_duration_ms:Math.round(durationMs||0),key_version:1},media_path:path,media_mime:mime,media_duration_ms:Math.round(durationMs||0)};const ins=await db.from('messages_v2').insert(payload).select('id,conversation_id,sender_id,message_type,created_at,encryption_version,ciphertext,encryption_metadata,media_path,media_mime,media_duration_ms').single();if(ins.error){await storage.from('private-voice').remove([path]).catch(()=>{});throw ins.error}return ins.data}
async function getUrl(storage,path){const r=await storage.from('private-voice').createSignedUrl(path,300);if(r.error)throw r.error;return r.data.signedUrl}
async function loadAndDecrypt(storage,path,rawKey,ivB64,aad){const r=await storage.from('private-voice').download(path);if(r.error)throw r.error;const plain=await decryptBytes(new Uint8Array(await r.data.arrayBuffer()),rawKey,unb64(ivB64),aad);return new Blob([plain],{type:'audio/webm'})}
global.WhatsAfricaVoice={preferredMime,startRecording,send,getUrl,loadAndDecrypt};
})(window);

/* Inbox enhancements: receipt state + conversation SmartLink sharing. Guarded to /inbox. */
(function(){'use strict';if(location.pathname!=='/inbox')return;const boot=()=>{const db=window.supabase?.createClient('https://dzifpwqrqnvssfhwjccj.supabase.co','sb_publishable_olHxhduENR5AnqUwAh8Qtw_4az5UmRV');if(!db)return;let shareBtn;
const setStatus=t=>{const el=document.getElementById('status');if(el){el.textContent=t;el.className='status ok'}};
async function shareConversation(){const c=window.current;if(!c?.id){setStatus('Ouvrez d’abord une conversation.');return}shareBtn.disabled=true;try{const r=await db.rpc('create_share_link',{p_resource_type:'conversation',p_resource_id:c.id,p_permission:'limited',p_expires_at:null,p_max_uses:null});if(r.error)throw r.error;const token=r.data?.token;if(!token)throw new Error('Lien SmartLink non généré');const url=location.origin+'/s/'+token;try{await navigator.share({title:c.title||'Conversation WhatsAfrica',text:'Rejoindre cette conversation sur WhatsAfrica',url})}catch(e){if(e?.name!=='AbortError'){await navigator.clipboard.writeText(url);setStatus('SmartLink copié.')}}setStatus('SmartLink de conversation prêt.')}catch(e){setStatus('Partage impossible : '+(e.message||'erreur'))}finally{shareBtn.disabled=false}}
function installHeader(){if(shareBtn||!document.getElementById('chat'))return;shareBtn=document.createElement('button');shareBtn.className='btn ghost';shareBtn.type='button';shareBtn.textContent='🔗 Partager';shareBtn.title='Créer un SmartLink sécurisé pour cette conversation';shareBtn.onclick=shareConversation;const call=document.getElementById('callCurrent');call?.parentElement?.appendChild(shareBtn)}
async function markReceipts(){const c=window.current,u=window.user;if(!c?.id||!u?.id||!db)return;const box=document.getElementById('messages');if(!box||!box.children.length)return;try{const q=await db.from('messages_v2').select('id,sender_id').eq('conversation_id',c.id).order('created_at',{ascending:false}).limit(50);if(q.error)throw q.error;await Promise.all((q.data||[]).filter(m=>m.sender_id!==u.id).map(m=>db.rpc('mark_message_receipt',{p_message_id:m.id,p_state:'delivered'})));await Promise.all((q.data||[]).filter(m=>m.sender_id!==u.id).map(m=>db.rpc('mark_message_receipt',{p_message_id:m.id,p_state:'read'})));}catch(e){console.warn('receipt sync',e)}}
function decorateOwnReceipts(){const c=window.current,u=window.user;if(!c?.id||!u?.id||!db)return;db.from('messages_v2').select('id,sender_id').eq('conversation_id',c.id).eq('sender_id',u.id).order('created_at',{ascending:false}).limit(50).then(async r=>{if(r.error)return;const ids=(r.data||[]).map(x=>x.id);if(!ids.length)return;const rr=await db.from('message_receipts').select('message_id,delivered_at,read_at').in('message_id',ids);if(rr.error)return;const map=new Map((rr.data||[]).map(x=>[x.message_id,x]));const nodes=Array.from(document.querySelectorAll('#messages .msg')).filter(n=>n.classList.contains('mine')).reverse();ids.reverse().forEach((id,i)=>{const node=nodes[i],rec=map.get(id);if(!node)return;let tick=node.querySelector('.wa-receipt');if(!tick){tick=document.createElement('span');tick.className='wa-receipt';tick.style.cssText='display:block;text-align:right;font-size:11px;opacity:.75;margin-top:3px';node.appendChild(tick)}tick.textContent=rec?.read_at?'✓✓ Lu':rec?.delivered_at?'✓✓ Livré':'✓ Envoyé'})}).catch(()=>{})}
const observer=new MutationObserver(()=>{installHeader();markReceipts();decorateOwnReceipts()});observer.observe(document.body,{subtree:true,childList:true});setInterval(()=>{installHeader();markReceipts();decorateOwnReceipts()},6000);setTimeout(()=>{installHeader();markReceipts();decorateOwnReceipts()},1200)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()})();