/* WhatsAfrica Voice — Android-stable encrypted voice media using the existing conversation AES key. */
(function(global){'use strict';
const te=new TextEncoder();
const b64=bytes=>{let s='';const a=new Uint8Array(bytes);for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s)};
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function key(raw){return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encryptBytes(bytes,rawKey,aad){const iv=crypto.getRandomValues(new Uint8Array(12));const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:te.encode(aad)},await key(rawKey),bytes));return{iv,ciphertext:ct}}
async function decryptBytes(bytes,rawKey,iv,aad){return new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:te.encode(aad)},await key(rawKey),bytes))}
function preferredMime(){if(typeof MediaRecorder==='undefined')return null;const types=['audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus','audio/ogg','audio/mp4'];return types.find(x=>{try{return MediaRecorder.isTypeSupported(x)}catch{return false}})||null}
function mimeBase(mime){return String(mime||'audio/webm').split(';')[0]}
function detectAudioMime(bytes,fallback){const b=new Uint8Array(bytes||[]);if(b.length>=4&&b[0]===0x1a&&b[1]===0x45&&b[2]===0xdf&&b[3]===0xa3)return'audio/webm';if(b.length>=4&&String.fromCharCode(...b.slice(0,4))==='OggS')return'audio/ogg';if(b.length>=8&&String.fromCharCode(...b.slice(4,8))==='ftyp')return'audio/mp4';return mimeBase(fallback)||'audio/webm'}
async function startRecording(){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Le microphone n’est pas disponible sur cet appareil ou ce navigateur.');const mime=preferredMime();if(!mime)throw new Error('Les messages vocaux ne sont pas pris en charge sur cet appareil.');let stream;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}})}catch(e){if(e?.name==='NotAllowedError')throw new Error('Autorisez le microphone dans les réglages Android pour envoyer un vocal.');if(e?.name==='NotFoundError')throw new Error('Aucun microphone disponible sur cet appareil.');throw new Error('Accès au microphone impossible.')}let recorder;try{recorder=new MediaRecorder(stream,{mimeType:mime})}catch(e){stream.getTracks().forEach(t=>t.stop());throw new Error('Le format audio choisi n’est pas compatible avec cet appareil.')}const chunks=[];const startedAt=Date.now();let settled=false;const cleanup=()=>stream.getTracks().forEach(t=>{try{t.stop()}catch{}});recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const done=new Promise((resolve,reject)=>{recorder.onstop=()=>{if(settled)return;settled=true;cleanup();const actualMime=mimeBase(chunks[0]?.type||mime);resolve({blob:new Blob(chunks,{type:actualMime}),durationMs:Math.max(0,Date.now()-startedAt),mime:actualMime})};recorder.onerror=e=>{if(settled)return;settled=true;cleanup();reject(e.error||new Error('Enregistrement vocal impossible'))};recorder.oninactive=()=>{if(!settled&&recorder.state!=='recording')recorder.stop()}});try{recorder.start(300)}catch(e){cleanup();throw new Error('Démarrage de l’enregistrement vocal impossible.')}return{recorder,done}}
async function send({db,storage,conversationId,senderId,rawKey,messageId,blob,durationMs,mime}){if(!db||!storage||!conversationId||!senderId||!rawKey||!blob)throw new Error('Message vocal invalide');if(blob.size>8*1024*1024)throw new Error('Message vocal trop volumineux (8 Mo maximum).');const id=messageId||crypto.randomUUID(),actualMime=mimeBase(mime||blob.type),aad=`whatsafrica:voice:v1:${conversationId}:${id}`,bytes=new Uint8Array(await blob.arrayBuffer()),enc=await encryptBytes(bytes,rawKey,aad),path=`${senderId}/${conversationId}/${id}.bin`,upload=await storage.from('private-voice').upload(path,new Blob([enc.ciphertext],{type:'application/octet-stream'}),{contentType:'application/octet-stream',upsert:false});if(upload.error)throw upload.error;const payload={id,conversation_id:conversationId,sender_id:senderId,body:null,message_type:'voice',audio_url:null,encryption_version:1,ciphertext:null,encryption_metadata:{v:1,kind:'voice',alg:'AES-256-GCM',iv:b64(enc.iv),aad,media_path:path,media_mime:actualMime,media_duration_ms:Math.round(durationMs||0),key_version:1},media_path:path,media_mime:actualMime,media_duration_ms:Math.round(durationMs||0)};const ins=await db.from('messages_v2').insert(payload).select('id,conversation_id,sender_id,message_type,created_at,encryption_version,ciphertext,encryption_metadata,media_path,media_mime,media_duration_ms').single();if(ins.error){await storage.from('private-voice').remove([path]).catch(()=>{});throw ins.error}return ins.data}
async function getUrl(storage,path){const r=await storage.from('private-voice').createSignedUrl(path,300);if(r.error)throw r.error;return r.data.signedUrl}
async function loadAndDecrypt(storage,path,rawKey,ivB64,aad,expectedMime){const r=await storage.from('private-voice').download(path);if(r.error)throw r.error;const bytes=new Uint8Array(await r.data.arrayBuffer()),plain=await decryptBytes(bytes,rawKey,unb64(ivB64),aad),mime=detectAudioMime(plain,expectedMime);return new Blob([plain],{type:mime})}
global.WhatsAfricaVoice={preferredMime,startRecording,send,getUrl,loadAndDecrypt};
})(window);

/* Inbox enhancements: receipt state + conversation SmartLink sharing. */
(function(){'use strict';
if(location.pathname!=='/inbox')return;
const URL='https://dzifpwqrqnvssfhwjccj.supabase.co',KEY='sb_publishable_olHxhduENR5AnqUwAh8Qtw_4az5UmRV';
let db=null,shareBtn=null,busy=false,lastConversationId=null,lastMessageCount=-1,lastSync=0;
const getDb=()=>db||(db=window.supabase?.createClient(URL,KEY));
const getActiveConversationId=()=>document.querySelector('.conv.active')?.dataset?.conversationId||new URLSearchParams(location.search).get('conversation');
const setStatus=t=>{const el=document.getElementById('status');if(el){el.textContent=t;el.className='status ok'}};
const currentUser=async()=>{const c=getDb();if(!c)return null;const r=await c.auth.getUser();return r.data?.user||null};
async function copyOrShare(url,title){try{if(navigator.share){await navigator.share({title,text:'Découvrez WhatsAfrica : ouvrez ce contenu et rejoignez la conversation.',url});return 'shared'}}catch(e){if(e?.name==='AbortError')return 'aborted'}try{await navigator.clipboard.writeText(url);return 'copied'}catch(e){const ta=document.createElement('textarea');ta.value=url;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();return 'copied'}}
async function shareConversation(){const c=getDb(),id=getActiveConversationId();if(!c||!id){setStatus('Ouvrez d’abord une conversation.');return}if(busy)return;busy=true;shareBtn?.setAttribute('disabled','disabled');try{const r=await c.rpc('create_share_link',{p_resource_type:'conversation',p_resource_id:id,p_permission:'limited',p_expires_at:null,p_max_uses:null});if(r.error)throw r.error;const token=r.data?.token||r.data?.[0]?.token;if(!token)throw new Error('Lien SmartLink non généré');const title=document.getElementById('chatTitle')?.textContent||'Conversation WhatsAfrica';const result=await copyOrShare(location.origin+'/s/'+token,title);if(result==='shared')setStatus('SmartLink WhatsAfrica partagé.');else if(result==='copied')setStatus('SmartLink WhatsAfrica copié.')}catch(e){setStatus('Partage impossible : '+(e.message||'erreur'))}finally{busy=false;shareBtn?.removeAttribute('disabled')}}
function installHeader(){const chat=document.getElementById('chat'),call=document.getElementById('callCurrent');if(!chat||!call||shareBtn&&document.body.contains(shareBtn))return;shareBtn=document.createElement('button');shareBtn.className='btn ghost wa-share-btn';shareBtn.type='button';shareBtn.textContent='🔗 Partager';shareBtn.title='Créer un SmartLink WhatsAfrica sécurisé pour cette conversation';shareBtn.addEventListener('click',shareConversation);call.parentElement?.appendChild(shareBtn)}
async function markReceipts(){const c=getDb(),id=getActiveConversationId(),box=document.getElementById('messages');if(!c||!id||!box||!box.children.length)return;const u=await currentUser();if(!u)return;try{const q=await c.from('messages_v2').select('id,sender_id').eq('conversation_id',id).order('created_at',{ascending:false}).limit(50);if(q.error)throw q.error;for(const m of(q.data||[])){if(m.sender_id===u.id)continue;await c.rpc('mark_message_receipt',{p_message_id:m.id,p_state:'delivered'}).catch(()=>{});await c.rpc('mark_message_receipt',{p_message_id:m.id,p_state:'read'}).catch(()=>{})}}catch(e){console.warn('receipt sync',e)}}
async function decorateOwnReceipts(){const c=getDb(),id=getActiveConversationId(),u=await currentUser();if(!c||!id||!u)return;try{const r=await c.from('messages_v2').select('id').eq('conversation_id',id).eq('sender_id',u.id).order('created_at',{ascending:true}).limit(50);if(r.error)return;const ids=(r.data||[]).map(x=>x.id);if(!ids.length)return;const rr=await c.from('message_receipts').select('message_id,delivered_at,read_at').in('message_id',ids);if(rr.error)return;const map=new Map((rr.data||[]).map(x=>[x.message_id,x]));const nodes=Array.from(document.querySelectorAll('#messages .msg')).filter(n=>n.classList.contains('mine'));const start=Math.max(0,ids.length-nodes.length);nodes.forEach((node,i)=>{const rec=map.get(ids[start+i]);if(!rec)return;let tick=node.querySelector('.wa-receipt');if(!tick){tick=document.createElement('span');tick.className='wa-receipt';tick.style.cssText='display:block;text-align:right;font-size:11px;opacity:.78;margin-top:3px';node.appendChild(tick)}tick.textContent=rec.read_at?'✓✓ Lu':rec.delivered_at?'✓✓ Livré':'✓ Envoyé'})}catch(e){console.warn('receipt display',e)}}
async function sync(){const id=getActiveConversationId(),count=document.querySelectorAll('#messages .msg').length;if(!id)return;const changed=id!==lastConversationId||count!==lastMessageCount||Date.now()-lastSync>10000;if(!changed){installHeader();return}lastConversationId=id;lastMessageCount=count;lastSync=Date.now();installHeader();if(busy)return;await markReceipts();await decorateOwnReceipts()}
const observer=new MutationObserver(()=>{installHeader();sync().catch(()=>{})});
observer.observe(document.body,{subtree:true,childList:true});
setTimeout(()=>sync().catch(()=>{}),1000);setInterval(()=>sync().catch(()=>{}),6000);
})();

/* Conversational microphone: speech-to-text input, distinct from encrypted voice messages. */
(function(){'use strict';
if(location.pathname!=='/inbox')return;
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
let recognition=null,listening=false,finalText='';
function status(t,kind){const el=document.getElementById('status');if(!el)return;el.textContent=t;el.className='status '+(kind||'muted')}
function language(){const l=(document.documentElement.lang||navigator.language||'fr').toLowerCase();return l.startsWith('en')?'en-US':l.startsWith('pt')?'pt-PT':l.startsWith('ar')?'ar-SA':'fr-FR'}
function install(){const composer=document.getElementById('composer'),body=document.getElementById('body'),voice=document.getElementById('voice');if(!composer||!body||!voice||composer.querySelector('.wa-speech-btn'))return;if(!SpeechRecognition){voice.title='Message vocal';return}const btn=document.createElement('button');btn.type='button';btn.className='btn ghost wa-speech-btn';btn.textContent='🗣️';btn.title='Parler pour écrire';btn.setAttribute('aria-label','Parler pour écrire un message');composer.insertBefore(btn,voice);btn.addEventListener('click',()=>{if(listening){recognition?.stop();return}recognition=new SpeechRecognition();recognition.lang=language();recognition.interimResults=true;recognition.continuous=false;recognition.maxAlternatives=1;finalText=body.value.trim();listening=true;btn.textContent='⏹️';btn.classList.add('gold');status('🎙️ Je vous écoute…','ok');recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0]?.transcript||'';if(e.results[i].isFinal)finalText=(finalText?finalText+' ':'')+text.trim();else interim+=text}body.value=(finalText+(interim?' '+interim:'')).trim();body.dispatchEvent(new Event('input',{bubbles:true}))};recognition.onerror=e=>{listening=false;btn.textContent='🗣️';btn.classList.remove('gold');status(e.error==='not-allowed'?'Autorisez le microphone pour utiliser la saisie vocale.':'Saisie vocale indisponible : '+e.error,'err')};recognition.onend=()=>{listening=false;btn.textContent='🗣️';btn.classList.remove('gold');body.focus();if(body.value.trim())status('Voix convertie en message. Appuyez sur ➤ pour envoyer.','ok');else status('Prêt.','muted')};recognition.start()});}
const observer=new MutationObserver(install);observer.observe(document.body,{subtree:true,childList:true});setTimeout(install,500);
})();