/* WhatsAfrica Voice — encrypted voice media using the existing conversation AES key. */
(function(global){'use strict';
const te=new TextEncoder();
const b64=bytes=>{let s='';const a=new Uint8Array(bytes);for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s)};
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function key(raw){return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encryptBytes(bytes,rawKey,aad){const iv=crypto.getRandomValues(new Uint8Array(12));const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:te.encode(aad)},await key(rawKey),bytes));return{iv,ciphertext:ct}}
async function decryptBytes(bytes,rawKey,iv,aad){return new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:te.encode(aad)},await key(rawKey),bytes))}
function preferredMime(){if(typeof MediaRecorder==='undefined')return null;const types=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4'];return types.find(x=>MediaRecorder.isTypeSupported(x))||null}
async function startRecording(){const mime=preferredMime();if(!mime)throw new Error('Les messages vocaux ne sont pas pris en charge sur cet appareil.');const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const recorder=new MediaRecorder(stream,{mimeType:mime});const chunks=[];const startedAt=Date.now();recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};const done=new Promise((resolve,reject)=>{recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());resolve({blob:new Blob(chunks,{type:mime.split(';')[0]}),durationMs:Date.now()-startedAt,mime:mime.split(';')[0]})};recorder.onerror=e=>{stream.getTracks().forEach(t=>t.stop());reject(e.error||new Error('Enregistrement vocal impossible'))}});recorder.start(250);return{recorder,done}}
async function send({db,storage,conversationId,senderId,rawKey,messageId,blob,durationMs,mime}){if(!db||!storage||!conversationId||!senderId||!rawKey||!blob)throw new Error('Message vocal invalide');if(blob.size>8*1024*1024)throw new Error('Message vocal trop volumineux (8 Mo maximum).');const id=messageId||crypto.randomUUID(),aad=`whatsafrica:voice:v1:${conversationId}:${id}`,bytes=new Uint8Array(await blob.arrayBuffer()),enc=await encryptBytes(bytes,rawKey,aad),path=`${senderId}/${conversationId}/${id}.bin`,upload=await storage.from('private-voice').upload(path,new Blob([enc.ciphertext],{type:'application/octet-stream'}),{contentType:'application/octet-stream',upsert:false});if(upload.error)throw upload.error;const payload={id,conversation_id:conversationId,sender_id:senderId,body:null,message_type:'voice',audio_url:null,encryption_version:1,ciphertext:null,encryption_metadata:{v:1,kind:'voice',alg:'AES-256-GCM',iv:b64(enc.iv),aad,media_path:path,media_mime:mime,media_duration_ms:Math.round(durationMs||0),key_version:1},media_path:path,media_mime:mime,media_duration_ms:Math.round(durationMs||0)};const ins=await db.from('messages_v2').insert(payload).select('id,conversation_id,sender_id,message_type,created_at,encryption_version,ciphertext,encryption_metadata,media_path,media_mime,media_duration_ms').single();if(ins.error){await storage.from('private-voice').remove([path]).catch(()=>{});throw ins.error}return ins.data}
async function getUrl(storage,path){const r=await storage.from('private-voice').createSignedUrl(path,300);if(r.error)throw r.error;return r.data.signedUrl}
async function loadAndDecrypt(storage,path,rawKey,ivB64,aad){const r=await storage.from('private-voice').download(path);if(r.error)throw r.error;const plain=await decryptBytes(new Uint8Array(await r.data.arrayBuffer()),rawKey,unb64(ivB64),aad);return new Blob([plain],{type:'audio/webm'})}
global.WhatsAfricaVoice={preferredMime,startRecording,send,getUrl,loadAndDecrypt};
})(window);