begin;
update public.smartlink_tariff_rules set monthly_amount=3500,trial_days=30,active=true,effective_until=null where id='584fd517-9d38-4bc7-ac13-306f5fed7085';
insert into public.smartlink_tariff_rules(country_code,region_code,plan_code,currency,monthly_amount,trial_days,effective_from,active)
select null,null,'pro','XOF',7500,30,now(),true where not exists(select 1 from public.smartlink_tariff_rules where country_code is null and region_code is null and plan_code='pro' and active=true);
insert into public.user_subscriptions(user_id,plan_code,status,started_at,ends_at,provider,provider_reference)
values('8bbaa0f3-a738-491e-9f20-d873ef0e2cbf','business','active',now(),null,'wassafrica','permanent_business_promarketer1er') on conflict do nothing;

create table if not exists public.wassafrica_partners(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete set null,partner_code text not null unique,display_name text not null,email text,phone text,country_code text not null,region text,city text,partner_type text not null check(partner_type in ('national_representative','ambassador','regional_partner','commercial_agent')),status text not null default 'pending' check(status in ('pending','active','suspended','inactive')),territory text,commission_rate numeric(6,3) not null default 0,target_monthly numeric(12,2) not null default 0,notes text,joined_at timestamptz not null default now(),last_activity_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.wassafrica_partner_activities(id uuid primary key default gen_random_uuid(),partner_id uuid not null references public.wassafrica_partners(id) on delete cascade,activity_type text not null,occurred_at timestamptz not null default now(),user_id uuid references auth.users(id) on delete set null,business_id uuid references public.businesses(id) on delete set null,country_code text,metadata jsonb not null default '{}'::jsonb);
create table if not exists public.wassafrica_partner_referrals(id uuid primary key default gen_random_uuid(),partner_id uuid not null references public.wassafrica_partners(id) on delete cascade,referred_user_id uuid references auth.users(id) on delete set null,referred_business_id uuid references public.businesses(id) on delete set null,referral_code text,status text not null default 'lead' check(status in ('lead','trial','converted','churned')),first_seen_at timestamptz not null default now(),converted_at timestamptz,metadata jsonb not null default '{}'::jsonb);
create table if not exists public.wassafrica_partner_commissions(id uuid primary key default gen_random_uuid(),partner_id uuid not null references public.wassafrica_partners(id) on delete cascade,referral_id uuid references public.wassafrica_partner_referrals(id) on delete set null,amount numeric(12,2) not null default 0,currency text not null default 'XOF',status text not null default 'pending' check(status in ('pending','approved','paid','cancelled')),period_start date,period_end date,paid_at timestamptz,created_at timestamptz not null default now());
alter table public.wassafrica_partners enable row level security;alter table public.wassafrica_partner_activities enable row level security;alter table public.wassafrica_partner_referrals enable row level security;alter table public.wassafrica_partner_commissions enable row level security;
drop policy if exists omnicto_deny_all on public.wassafrica_partners;drop policy if exists omnicto_deny_all on public.wassafrica_partner_activities;drop policy if exists omnicto_deny_all on public.wassafrica_partner_referrals;drop policy if exists omnicto_deny_all on public.wassafrica_partner_commissions;
create policy omnicto_deny_all on public.wassafrica_partners as restrictive for all to public using(false) with check(false);
create policy omnicto_deny_all on public.wassafrica_partner_activities as restrictive for all to public using(false) with check(false);
create policy omnicto_deny_all on public.wassafrica_partner_referrals as restrictive for all to public using(false) with check(false);
create policy omnicto_deny_all on public.wassafrica_partner_commissions as restrictive for all to public using(false) with check(false);
revoke all on public.wassafrica_partners,public.wassafrica_partner_activities,public.wassafrica_partner_referrals,public.wassafrica_partner_commissions from public,anon,authenticated;

create or replace function public.smartlink_current_tariff() returns jsonb language plpgsql stable security definer set search_path='' as $$
declare v_uid uuid:=auth.uid();v_country text;v_region text;v_trial timestamptz;v_paid boolean:=false;v_plan text:='starter';v_rule public.smartlink_tariff_rules%rowtype;v_trial_end timestamptz;
begin if v_uid is null then raise exception 'AUTH_REQUIRED';end if;
select upper(nullif(trim(p.country),'')),nullif(trim(p.city),''),p.trial_ends_at into v_country,v_region,v_trial from public.profiles p where p.user_id=v_uid for update;
select case when exists(select 1 from public.user_subscriptions s where s.user_id=v_uid and s.plan_code='pro' and s.status in ('trialing','active','past_due') and (s.ends_at is null or s.ends_at>now())) then 'pro' else 'starter' end into v_plan;
select r.* into v_rule from public.smartlink_tariff_rules r where r.plan_code=v_plan and r.active and r.effective_from<=now() and (r.effective_until is null or r.effective_until>now()) and (r.country_code is null or lower(r.country_code)=lower(v_country)) and (r.region_code is null or lower(r.region_code)=lower(v_region)) order by (r.region_code is not null) desc,(r.country_code is not null) desc,r.effective_from desc limit 1;
if v_rule.id is null then raise exception 'SMARTLINK_TARIFF_NOT_CONFIGURED';end if;
select exists(select 1 from public.user_subscriptions s where s.user_id=v_uid and s.plan_code in ('starter','pro') and s.status in ('trialing','active','past_due') and (s.ends_at is null or s.ends_at>now())) into v_paid;
if v_trial is null and not v_paid and v_rule.trial_days>0 then v_trial_end:=now()+make_interval(days=>v_rule.trial_days);update public.profiles set trial_ends_at=v_trial_end where user_id=v_uid;insert into private.trial_ledger(user_id,claimed_at,trial_ends_at,source,metadata) values(v_uid,now(),v_trial_end,'smartlink_auto',jsonb_build_object('service','smartlink','tariff_id',v_rule.id,'country_code',v_country)) on conflict(user_id) do nothing;select trial_ends_at into v_trial from public.profiles where user_id=v_uid;end if;
return jsonb_build_object('service','smartlink','plan_code',v_plan,'country_code',v_country,'region_code',v_region,'currency',v_rule.currency,'monthly_amount',v_rule.monthly_amount,'trial_days',v_rule.trial_days,'trial_ends_at',v_trial,'trial_active',coalesce(v_trial>now(),false),'paid_active',v_paid,'paid_required',not(coalesce(v_trial>now(),false) or v_paid),'effective_from',v_rule.effective_from,'effective_until',v_rule.effective_until);end $$;

create or replace function public.admin_partner_overview(p_days integer default 30) returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$
declare d integer:=greatest(1,least(coalesce(p_days,30),365));begin if auth.uid() is null or not public.is_platform_admin() then raise exception using errcode='42501',message='admin_required';end if;return jsonb_build_object('period_days',d,'partners_total',(select count(*) from public.wassafrica_partners),'partners_active',(select count(*) from public.wassafrica_partners where status='active'),'countries',(select count(distinct country_code) from public.wassafrica_partners where status='active'),'activities',(select count(*) from public.wassafrica_partner_activities where occurred_at>=now()-make_interval(days=>d)),'referrals',(select count(*) from public.wassafrica_partner_referrals where first_seen_at>=now()-make_interval(days=>d)),'conversions',(select count(*) from public.wassafrica_partner_referrals where status='converted' and converted_at>=now()-make_interval(days=>d)),'commission_pending',(select coalesce(sum(amount),0) from public.wassafrica_partner_commissions where status='pending'),'commission_paid',(select coalesce(sum(amount),0) from public.wassafrica_partner_commissions where status='paid'),'by_country',coalesce((select jsonb_agg(x order by x.active_partners desc) from(select country_code,count(*) filter(where status='active') active_partners,count(*) total_partners from public.wassafrica_partners group by country_code)x),'[]'::jsonb),'leaderboard',coalesce((select jsonb_agg(x order by x.conversions desc,x.activities desc) from(select p.id,p.partner_code,p.display_name,p.partner_type,p.country_code,p.city,p.status,count(a.id) filter(where a.occurred_at>=now()-make_interval(days=>d)) activities,count(r.id) filter(where r.status='converted' and r.converted_at>=now()-make_interval(days=>d)) conversions,coalesce(sum(c.amount) filter(where c.status in ('approved','paid')),0) commissions from public.wassafrica_partners p left join public.wassafrica_partner_activities a on a.partner_id=p.id left join public.wassafrica_partner_referrals r on r.partner_id=p.id left join public.wassafrica_partner_commissions c on c.partner_id=p.id group by p.id,p.partner_code,p.display_name,p.partner_type,p.country_code,p.city,p.status)x),'[]'::jsonb'));end $$;
revoke all on function public.admin_partner_overview(integer) from public,anon,authenticated;grant execute on function public.admin_partner_overview(integer) to authenticated;
commit;