drop policy if exists business_owners_and_members_manage_products_insert on public.products;
drop policy if exists business_owners_and_members_manage_products_update on public.products;
drop policy if exists business_owners_and_members_manage_products_delete on public.products;
drop policy if exists "public products" on public.products;
create policy business_owners_and_members_manage_products_insert on public.products for insert to authenticated with check (exists (select 1 from public.businesses b where b.id=products.business_id and b.smartlink_tier in ('free','starter','business','premium') and (b.owner_id=auth.uid() or exists (select 1 from public.business_members bm where bm.business_id=b.id and bm.user_id=auth.uid() and bm.role in ('owner','admin','sales'))) and (b.smartlink_tier='free' or exists (select 1 from public.user_subscriptions s where s.user_id=auth.uid() and s.plan_code=b.smartlink_tier and s.status='active' and (s.ends_at is null or s.ends_at>now())))));
create policy business_owners_and_members_manage_products_update on public.products for update to authenticated using (exists (select 1 from public.businesses b where b.id=products.business_id and b.smartlink_tier in ('free','starter','business','premium') and (b.owner_id=auth.uid() or exists (select 1 from public.business_members bm where bm.business_id=b.id and bm.user_id=auth.uid() and bm.role in ('owner','admin','sales'))))) with check (exists (select 1 from public.businesses b where b.id=products.business_id and b.smartlink_tier in ('free','starter','business','premium') and (b.owner_id=auth.uid() or exists (select 1 from public.business_members bm where bm.business_id=b.id and bm.user_id=auth.uid() and bm.role in ('owner','admin','sales'))) and (b.smartlink_tier='free' or exists (select 1 from public.user_subscriptions s where s.user_id=auth.uid() and s.plan_code=b.smartlink_tier and s.status='active' and (s.ends_at is null or s.ends_at>now())))));
create policy business_owners_and_members_manage_products_delete on public.products for delete to authenticated using (exists (select 1 from public.businesses b where b.id=products.business_id and b.smartlink_tier in ('free','starter','business','premium') and (b.owner_id=auth.uid() or exists (select 1 from public.business_members bm where bm.business_id=b.id and bm.user_id=auth.uid() and bm.role in ('owner','admin','sales'))) and (b.smartlink_tier='free' or exists (select 1 from public.user_subscriptions s where s.user_id=auth.uid() and s.plan_code=b.smartlink_tier and s.status='active' and (s.ends_at is null or s.ends_at>now())))));
create policy "public products" on public.products for select to anon,authenticated using (is_published=true and exists (select 1 from public.businesses b where b.id=products.business_id and (b.smartlink_tier='free' or exists (select 1 from public.user_subscriptions s where s.user_id=b.owner_id and s.plan_code=b.smartlink_tier and s.status='active' and (s.ends_at is null or s.ends_at>now())))));

drop policy if exists marketplace_services_owner_insert on public.marketplace_services;
drop policy if exists marketplace_services_owner_update on public.marketplace_services;
drop policy if exists marketplace_select_published_or_owner on public.marketplace_services;
create policy marketplace_services_owner_insert on public.marketplace_services for insert to authenticated with check (seller_id=auth.uid() and (exists (select 1 from public.businesses b where b.owner_id=auth.uid() and b.smartlink_tier='free') or exists (select 1 from public.user_subscriptions s where s.user_id=auth.uid() and s.plan_code in ('starter','business','premium') and s.status='active' and (s.ends_at is null or s.ends_at>now()))));
create policy marketplace_services_owner_update on public.marketplace_services for update to authenticated using (seller_id=auth.uid()) with check (seller_id=auth.uid() and (exists (select 1 from public.businesses b where b.owner_id=auth.uid() and b.smartlink_tier='free') or exists (select 1 from public.user_subscriptions s where s.user_id=auth.uid() and s.plan_code in ('starter','business','premium') and s.status='active' and (s.ends_at is null or s.ends_at>now()))));
create policy marketplace_select_published_or_owner on public.marketplace_services for select to anon,authenticated using ((status='published' and (exists (select 1 from public.businesses b where b.owner_id=marketplace_services.seller_id and b.smartlink_tier='free') or exists (select 1 from public.user_subscriptions s where s.user_id=marketplace_services.seller_id and s.plan_code in ('starter','business','premium') and s.status='active' and (s.ends_at is null or s.ends_at>now())))) or auth.uid()=seller_id);