async function fetchImportedImage(imageUrl,res){const u=new URL(imageUrl);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return res.status(400).json({error:'INVALID_IMAGE_URL'});if(u.port&&u.port!=='80'&&u.port!=='443')return res.status(400).json({error:'INVALID_IMAGE_PORT'});const host=u.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.localhost')||host==='127.0.0.1'||host==='::1'||host.startsWith('127.')||host.startsWith('10.')||host.startsWith('192.168.')||host.startsWith('169.254.')||host.startsWith('172.16.')||host.startsWith('172.17.')||host.startsWith('172.18.')||host.startsWith('172.19.')||host.startsWith('172.2')||host.startsWith('172.30.')||host.startsWith('172.31.')||host.endsWith('.internal'))return res.status(400).json({error:'BLOCKED_HOST'});const ac=new AbortController();const timer=setTimeout(()=>ac.abort(),10000);let r;try{r=await fetch(imageUrl,{method:'GET',redirect:'manual',signal:ac.signal,headers:{'User-Agent':'WASSAFRICA Smart Link Image Import/1.0','Accept':'image/avif,image/webp,image/png,image/jpeg,image/gif'}})}finally{clearTimeout(timer)}if(r.status>=300&&r.status<400)return res.status(400).json({error:'REDIRECT_NOT_ALLOWED'});if(!r.ok)return res.status(502).json({error:'IMAGE_FETCH_FAILED',status:r.status});const type=(r.headers.get('content-type')||'').split(';')[0].toLowerCase();if(!/^image\/(jpeg|png|webp|gif|avif)$/.test(type))return res.status(415).json({error:'NOT_AN_IMAGE'});const len=Number(r.headers.get('content-length')||0);if(len>5*1024*1024)return res.status(413).json({error:'IMAGE_TOO_LARGE'});const buf=Buffer.from(await r.arrayBuffer());if(buf.length>5*1024*1024)return res.status(413).json({error:'IMAGE_TOO_LARGE'});res.setHeader('Content-Type',type);res.setHeader('Cache-Control','private, max-age=300');res.setHeader('X-Content-Type-Options','nosniff');return res.status(200).send(buf)}\nexport default async function handler(req,res){
  if(req.method!=='POST')return res.status(405).json({error:'METHOD_NOT_ALLOWED'});
  try{
    if(req.body?.image_url){const imageUrl=String(req.body.image_url).trim();if(!/^https?:\/\//i.test(imageUrl))return res.status(400).json({error:'INVALID_IMAGE_URL'});return await fetchImportedImage(imageUrl,res)}
    const urls=Array.isArray(req.body?.urls)?req.body.urls.filter(x=>typeof x==='string').map(x=>x.trim()).filter(Boolean).slice(0,20):[];
    if(!urls.length)return res.status(400).json({error:'NO_URLS'});
    if(urls.some(u=>!/^https?:\/\//i.test(u)))return res.status(400).json({error:'INVALID_URL'});
    const key=process.env.OPENAI_API_KEY;
    if(!key)return res.status(503).json({error:'AI_NOT_CONFIGURED',message:'L’IA Smart Link nécessite OPENAI_API_KEY dans Vercel.'});
    const prompt=`Tu es l'assistant commercial de WASSAFRICA. Analyse les pages correspondant aux URLs fournies avec la recherche web. Pour chaque URL, crée UNE offre exploitable dans un Smart Link. Ne fabrique jamais un prix, une caractéristique ou une disponibilité absente de la source. Si une donnée manque, mets null ou une chaîne vide. Retourne uniquement un objet JSON avec une clé "offers", tableau de 1 à 20 objets. Champs: title, description, price(number|null), currency(string), stock(number|null), category, product_type(physical|digital|service), source_url, image_urls(array of up to 5 public image URLs). Ne renvoie que des images publiques réellement présentes sur la page si elles sont identifiables. URLs: ${urls.join('\n')}`;
    const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.6-luna',tools:[{type:'web_search'}],input:prompt,text:{format:{type:'json_schema',name:'smartlink_offers',strict:true,schema:{type:'object',properties:{offers:{type:'array',items:{type:'object',properties:{title:{type:'string'},description:{type:'string'},price:{type:['number','null']},currency:{type:'string'},stock:{type:['number','null']},category:{type:'string'},product_type:{type:'string',enum:['physical','digital','service']},source_url:{type:'string'},image_urls:{type:'array',items:{type:'string'},maxItems:5}},required:['title','description','price','currency','stock','category','product_type','source_url','image_urls'],additionalProperties:false}}},required:['offers'],additionalProperties:false}}}})});
    const j=await r.json();
    if(!r.ok)return res.status(502).json({error:'AI_REQUEST_FAILED',detail:j?.error?.message||'Erreur IA'});
    const out=j.output_text||j.output?.map(x=>x.content?.map(y=>y.text||'').join('')).join('');
    let data;try{data=JSON.parse(out)}catch{throw new Error('AI_INVALID_JSON')}
    return res.status(200).json(data);
  }catch(e){return res.status(500).json({error:'IMPORT_FAILED',message:e.message||'Erreur import IA'})}
}